### ISSUE TITLE
undefined timeout behavior

### ISSUE THREAD

**Issue by cyberjq** [shunyeka/mongo_queue#1]
@shunyeka, timeout in the Queue class in days. I guess the correct timeout behavior is in seconds. 

https://github.com/shunyeka/mongo_queue/blob/7700b5f1050515e4d9714d480f2d1cd7e4641c36/mongo_queue/queue.py#L18

I assume that this happens because the seconds parameter is not explicitly specified (days by default)

https://github.com/shunyeka/mongo_queue/blob/7700b5f1050515e4d9714d480f2d1cd7e4641c36/mongo_queue/queue.py#L76

**Comment by AmitChotaliya** [comment]
@Kanalias  thanks for reporting the issue. I have fixed and pushed a new version 0.0.8.
